version: '3.8'

services:
  mongo-db:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Carlos23
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
